[backends]
  [backends.nodelocal]
    [backends.nodelocal.servers.server1]
    url = "http://192.168.1.157:7014"
[frontends]
  [frontends.nodelocal]
  backend = "nodelocal"
    [frontends.nodelocal.routes.test_1]
    rule = "Host:nodelocal.localhost"
